### ISSUE TITLE
header name is not work in okhttp3 3.6.0

### ISSUE THREAD

**Issue by ben-upsilon** [upyun/android-sdk#12]
java.lang.IllegalArgumentException
Unexpected char 0x20 at 19 in header name: x-upyun-api-version
com.upyun.library.common.UploadClient.fromUpLoad(UploadClient.java:45)
看了一下okhttp3 的 change log
https://github.com/square/okhttp/commit/731a2628bf4a7f925ac71950d3670a9e1e6fbfeb
这里说明header的name末尾带空格也丢异常了。

**Comment by yemingm** [comment]
ok thanks
