### ISSUE TITLE
1.0.3版本没有UploadEngine

### ISSUE THREAD

**Issue by huaweihulk** [upyun/android-sdk#16]
如题

**Comment by yudapiandroid** [comment]
好像变成 UploadManager了~~ 略坑~~

**Comment by yemingm** [comment]
UploadEngine 是 2.XX 新加入的接口，使用新的签名策略，UploadManager  是 1.XX  的使用的接口更新后保留但提示已过期不推荐使用。

**Comment by huaweihulk** [comment]
好吧，之前更新README，没有更新对应的版本号吧。。。。。
