### ISSUE TITLE
小部分机型会报授权过期

### ISSUE THREAD

**Issue by oubowu** [upyun/android-sdk#6]
{"code":403,"url":"...路径保密.../2016-06-10-10-39-27-1465526255493.jpg","time":1465526370,"message":"authorization has expired","no-sign":"837b74f21bdc9a890eda65e141554373"}

**Comment by yemingm** [comment]
机型？还有网络请求能抓包看下吗？

**Comment by oubowu** [comment]
解决了，代码问题
