### ISSUE TITLE
服务器生成了policy和Signature 返回给我，应该怎么使用

### ISSUE THREAD

**Issue by bethinner** [upyun/android-sdk#9]
有以下几点问题，ps，用的formUpload提交
1:app端还是需要设置BUCKET？如何设置；
2:在SignatureListener的
getSignature(String policy) {
                return 
            }
我应该return什么值，试了好几种情况都是报 signature error

**Comment by yemingm** [comment]
按照 README 上的说明将 SignatureListener 提供的的参数 raw 上传给服务器，让服务器做一次 raw 和 保存在服务器的 KEY 拼接，拼接结果做一次 MD5 返回客户端，在这个 Listenter 下 return 即可。可以参考下DEMO 示例代码。

**Comment by bethinner** [comment]
@yemingm 但是我们的后台服务器的接口为了保证空间和路径都可以服务器控制，所以SignatureListener提供的参数raw也是服务器生成好给我的，而不是我通过android sdk设置相关参数之后从SignatureListener里面拿到
